add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status$python]($style)$character"

[character]
error_symbol = "[✗](bold #f6c177)"
success_symbol = "[❯](bold #f6c177)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = "bold #f6c177"
repo_root_style = "bold #f6c177"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic #f6c177"

[git_status]
format     = '[$all_status]($style)'
style      = "#f6c177"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = "? "

[python]
symbol = " "
pyenv_version_name = true
format = "[$symbol($virtualenv )]($style)"
style = "bold yellow"
disabled = false
# Aggiungi queste linee per mostrare solo con virtualenv attivo
detect_extensions = []
detect_files = []
detect_folders = []
